name: PDF Batch Compressor

on:
  # Запускать по расписанию (в рабочее время по будням каждые 2 часа)
  # 8:00, 10:00, 12:00, 14:00, 16:00 UTC = 9:00, 11:00, 13:00, 15:00, 17:00 CET (по будням: пн-пт)
  schedule:
    - cron: '0 8,10,12,14,16 * * 1-5'

  # Позволить запускать вручную
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript qpdf
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run PDF Compressor
        env:
          MEGA_EMAIL: ${{ secrets.MEGA_EMAIL }}
          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}
        run: |
          python src/main.py --log-level INFO
      
      - name: Upload logs to artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: compression-logs
          path: temp/logs/
          retention-days: 30

